# Generated by Django 3.2.7 on 2021-09-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulePlanner', '0003_auto_20210928_1646'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
