# Generated by Django 3.2.7 on 2021-11-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulePlanner', '0005_auto_20211110_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
