# Generated by Django 3.2.7 on 2021-12-08 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulePlanner', '0006_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('Student', 'Student'), ('Advisor', 'Advisor'), ('Faculty', 'Faculty'), ('Admin', 'Admin')], default='Student'),
        ),
        migrations.CreateModel(
            name='CourseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulePlanner.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='planned_credits',
            field=models.ManyToManyField(through='SchedulePlanner.CourseLog', to='SchedulePlanner.Course'),
        ),
    ]
