# Generated by Django 3.2.7 on 2021-12-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulePlanner', '0007_auto_20211207_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateField(),
        ),
    ]
