# Generated by Django 3.2.7 on 2021-12-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulePlanner', '0008_alter_courselog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselog',
            name='taken',
            field=models.BooleanField(default='False'),
        ),
    ]
